version: "3.4"
services:
    plex:
        image: linuxserver/plex
        container_name: plex
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
            - UMASK_SET=022 #optional
            - PLEX_CLAIM= #optional
        volumes:
            - ./volumes/plex/library:/config
            - downloads:/tv
            - downloads:/movies
        restart: unless-stopped
        ports:
            - "32400:32400"
            - "1900:1900"
            - "3005:3005"
            - "5353:5353"
            - "8324:8324"
            - "32410:32410"
            - "32412:32412"
            - "32413:32413"
            - "32414:32414"
            - "32469:32469"
  

    deluge:
        image: linuxserver/deluge
        container_name: deluge
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - UMASK_SET=022 #optional
            - DELUGE_LOGLEVEL=error #optional
        volumes:
            - ./volumes/deluge/config:/config
            - downloads:/downloads
        restart: unless-stopped
        ports:
            - "8080:80"


    samba:
        container_name: samba
        hostname: samba
        image: sixeyed/samba
        volumes:
            - downloads:/downloads
        ports:
            - "139:139"
            - "445:445"
            - "137:137/udp"
            - "138:138/udp"
        command: samba.sh -s "downloads;/downloads;yes;no;yes;all" 
        restart: unless-stopped
        network_mode: host

volumes:
    downloads:       