version: "3.4"
services:
    plex:
        image: linuxserver/plex
        container_name: plex
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
            - UMASK_SET=022 #optional
            - PLEX_CLAIM= #optional
        volumes:
            - ./volumes/plex/library:/config:rw
            - downloads:/media:rw
        restart: unless-stopped
        ports:
            - "32400:32400"
            - "1900:1900"
            - "3005:3005"
            - "5353:5353"
            - "8324:8324"
            - "32410:32410"
            - "32412:32412"
            - "32413:32413"
            - "32414:32414"
            - "32469:32469"
  

    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
            - USER=pi #optional
            - PASS=raspberry #optional
        volumes:
            - ./volumes/transmission/config:/config
            - downloads:/downloads
            - ./volumes/transmission/watch:/watch
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped


    samba:
        container_name: samba
        hostname: samba
        image: sixeyed/samba
        volumes:
            - downloads:/downloads:rw
        ports:
            - "139:139"
            - "4445:445"
            - "137:137/udp"
            - "138:138/udp"
        command: samba.sh -s "downloads;/downloads;yes;no;yes;all" 
        restart: unless-stopped
        network_mode: host


volumes:
    external_hdd:
    downloads:
    downloading:
